resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.8"

resources:
- name: greet-service
  type: git
  source:
    uri: https://github.com/sneakybeaky/toy-go-microservices.git
    branch: master
    ignore_paths:
    - version
    - README.md

- name: greetservice-image
  type: docker-image
  source:
    repository: 102184001161.dkr.ecr.us-east-1.amazonaws.com/test-front-service
    aws_access_key_id: ((aws_ecr_access_key_id))
    aws_secret_access_key: ((aws_ecr_secret_access_key))

- name: kubernetes-production
  type: kubernetes
  source:
    server: ((k8s_api_url))
    namespace: production
    token: ((k8s_token))
    certificate_authority: ((k8s_ca_cert))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:sneakybeaky/toy-go-microservices.git
    branch: version
    file: version
    private_key: ((version-repo-private-key))
    depth: 1
    initial_version: 0.0.1


jobs:
- name: publish-image
  plan:
  - get: greet-service
    trigger: true
  - put: version
    params: {bump: patch}
  - put: greetservice-image
    params:
      build: greet-service
      tag: version/version
      tag_as_latest: true


- name: deploy
  plan:
  - get: version
    passed: [publish-image]
  - get: greet-service
    passed: [publish-image]
  - task: assemble-k8s-template
    file: greet-service/ci/tasks/assemble-k8s-template.yaml
  - put: kubernetes-production
    params:
      kubectl: apply -f k8s-template/deploy.yaml
      wait_until_ready_selector: app=front-service


