---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: 'latest'

inputs:
- name: string-service
  path: source

outputs:
- name: helm-chart

run:
  path: source/string/ci/tasks/scripts/package-chart.sh