---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: version
- name: greet-service

outputs: k8s-template

run:
  path: ./greet-service/ci/tasks/scripts/assemble-k8s-template.sh