---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: version
- name: greet-service
  path: source

outputs:
- name: kubernetes-template

run:
  path: source/greet/ci/tasks/scripts/assemble-template.sh