---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: version
- name: service
  path: greet-service/greet

outputs:
- name: kubernetes-template

run:
  path: greet-service/ci/tasks/scripts/assemble-template.sh