---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hairyhenderson/gomplate
    tag: 'v2.2.0'

params:
  DOCKER_IMAGE:
  VERSION_FILE:
  DIGEST_FILE:

inputs:
- name: version
- name: greetservice-image
- name: greet-service
  path: source

outputs:
- name: kubernetes-template

run:
  path: source/greet/ci/tasks/scripts/assemble-template.sh