apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: greet-service
  labels:
    app: greet-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greet-service
  template:
    metadata:
      labels:
        app: greet-service
    spec:
      containers:
      - name: greet-service
        image: 102184001161.dkr.ecr.us-east-1.amazonaws.com/tolley/greet-service:
        ports:
        - containerPort: 8080
        env:
        - name: stringsvc
          value: "http://stringsvc:8080"
