apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: greet-service
  labels:
    app: greet-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greet-service
  template:
    metadata:
      labels:
        app: greet-service
    spec:
      containers:
      - name: greet-service
        image: {{env.Getenv "DOCKER_IMAGE"}}@{{env.Getenv "DIGEST"}}
        ports:
        - containerPort: 8080
        env:
        - name: stringsvc
          value: "http://stringsvc:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: greet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: greet-service
  type: LoadBalancer