apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
      - name: front-service
        image: 102184001161.dkr.ecr.us-east-1.amazonaws.com/test-front-service:
        ports:
        - containerPort: 8080
        env:
        - name: stringsvc
          value: "http://stringsvc:8080"
