resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.8"

resources:
- name: greet-service
  type: git
  source:
    uri: https://github.com/sneakybeaky/toy-go-microservices.git
    branch: master
    paths:
    - greet/*

- name: greetservice-image
  type: docker-image
  source:
    repository: ((ecr_repo))
    aws_access_key_id: ((aws_ecr_access_key_id))
    aws_secret_access_key: ((aws_ecr_secret_access_key))

- name: kubernetes-production
  type: kubernetes
  source:
    server: ((k8s_api_url))
    namespace: default
    token: ((k8s_token))
    insecure_skip_tls_verify: true

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:sneakybeaky/toy-go-microservices.git
    branch: version
    file: greet/version
    private_key: ((version-repo-private-key))
    depth: 1
    initial_version: 0.0.0


jobs:
- name: publish-image
  plan:
  - get: greet-service
    trigger: true
  - put: version
    params: {bump: patch}
  - put: greetservice-image
    params:
      build: greet-service/greet
      tag: version/version
      tag_as_latest: true


- name: deploy
  plan:
  - get: version
    passed: [publish-image]
  - get: greet-service
    passed: [publish-image]
  - task: assemble-template
    file: greet-service/greet/ci/tasks/assemble-template.yaml
  - put: kubernetes-production
    params:
      kubectl: apply -f kubernetes-template/deploy.yaml
      wait_until_ready_selector: app=front-service


