resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: golang-image
  type: docker-image
  source:
    repository: golang
    tag: 1.9

- name: greet-service
  type: git
  source:
    uri: https://github.com/sneakybeaky/toy-go-microservices.git
    branch: master
    paths:
    - greet/*

- name: greetservice-image
  type: docker-image
  source:
    repository: ninedemons/greet
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: greetservice-helm
  type: helm
  source:
    cluster_url: https://kubernetes.default.svc
    cluster_ca: ((k8s_ca))
    token: ((k8s_bearer_token))
    release: greet-service

jobs:
- name: publish-image
  plan:
  - aggregate:
    - get: golang-image
      params: { save: true }
    - get: greet-service
      trigger: true
  - put: greetservice-image
    params:
      load_base: golang-image
      build: greet-service/greet
      tag_as_latest: true

- name: deploy
  plan:
  - aggregate:
    - get: greetservice-image
      passed: [publish-image]
    - get: greet-service
      passed: [publish-image]
  - task: package-chart
    file: greet-service/greet/ci/tasks/package-chart.yaml
  - put: greetservice-helm
    params:
      chart: helm-chart/chart.tgz
      override_values:
      - key: image.digest
        path: greetservice-image/digest

