apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: string-service
  labels:
    app: string-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: string-service
  template:
    metadata:
      labels:
        app: string-service
    spec:
      containers:
      - name: string-service
        image: {{env.Getenv "DOCKER_IMAGE"}}@{{env.Getenv "DIGEST"}}
        ports:
        - containerPort: 8080