apiVersion: v1
kind: Service
metadata:
  name: {{ template "greetservice.fullname" . }}
  labels:
    app: {{ template "greetservice.name" . }}
    chart: {{ template "greetservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/probe: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "greetservice.name" . }}
    release: {{ .Release.Name }}
  type: LoadBalancer