resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: golang-image
  type: docker-image
  source:
    repository: golang
    tag: 1.9

- name: string-service
  type: git
  source:
    uri: https://github.com/sneakybeaky/toy-go-microservices.git
    branch: master
    paths:
    - string/*

- name: stringservice-image
  type: docker-image
  source:
    repository: ninedemons/string
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: stringservice-helm
  type: helm
  source:
    cluster_url: https://kubernetes.default.svc
    cluster_ca: ((k8s_ca))
    token: ((k8s_bearer_token))
    release: string-service

jobs:
- name: publish-image
  plan:
  - aggregate:
    - get: golang-image
      params: { save: true }
    - get: string-service
      trigger: true
  - put: stringservice-image
    params:
      load_base: golang-image
      build: string-service/string
      tag_as_latest: true

- name: deploy
  plan:
  - aggregate:
    - get: stringservice-image
      passed: [publish-image]
    - get: string-service
      passed: [publish-image]
  - task: package-chart
    file: string-service/string/ci/tasks/package-chart.yaml
  - put: stringservice-helm
    params:
      chart: helm-chart/chart.tgz
      override_values:
      - key: image.digest
        path: stringservice-image/digest

